In [2]:
import numpy as np

twoD = np.array([[1,2,3,4],[6,5,4,9],[11,22,33,44],[15,12,1,3]])
print(twoD)

[[ 1  2  3  4]
 [ 6  5  4  9]
 [11 22 33 44]
 [15 12  1  3]]


In [3]:
#inserting new elements instide the two dimansional array
newArray = np.insert(twoD, 0,[[8,5,2,3]], axis = 1)
print(newArray)

[[ 8  1  2  3  4]
 [ 5  6  5  4  9]
 [ 2 11 22 33 44]
 [ 3 15 12  1  3]]


In [4]:
#accessing two dimansional array
def accessElements(array, rowIndex, columnIndex):
    if rowIndex >= len(array) and cloumnIndex >= len(array[0]):
        print("invalid arrY")
        
    else:
        
        print(array[rowIndex][columnIndex])
        
accessElements(newArray,1,2)
            

5


In [10]:
#traversing the two dimansional array

def traverse(array):
        for i in range(len(array)):
            for j in range(len(array[0])):
                           print(array[i][j])
                       
traverse(newArray)                   

8
1
2
3
4
5
6
5
4
9
2
11
22
33
44
3
15
12
1
3


In [12]:
#searching in the two dimensional array
 
def search(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'the value i located at index: '+str(i)+" "+str(j)
    return "the element is not found"


search(newArray, 44)

'the value i slocated at index: 2 4'

In [13]:
#deleting an element from an two dimensional array
dArray = np.delete(newArray, 0, axis = 1)
print(dArray)



[[ 1  2  3  4]
 [ 6  5  4  9]
 [11 22 33 44]
 [15 12  1  3]]
